version: '3'

configs:
  git-remote-ssh-authorized-keys:
    file: ./git-remote-ssh-authorized-keys/authorized_keys

services:
  git_remote:
    image: ssh-server:ubuntu-latest    
    volumes:
      - type: bind
        source: ./git-remote-root
        target: /git-root
      - type: bind
        source: ./git-remote-ssh-authorized-keys/authorized_keys
        target: /git/.ssh/authorized_keys
    ports:
      - "2222:22"
  redis:
    image: redis
    volumes:
      - type: bind
        source: ./redis-data
        target: /data
    ports:
      - "6379:6379"
  gerrit:
    image: gerritcodereview/gerrit
    volumes:
      - type: bind
        source: ./gerrit-root/git
        target: /var/gerrit/git
      - type: bind
        source: ./gerrit-root/index
        target: /var/gerrit/index
      - type: bind
        source: ./gerrit-root/cache
        target: /var/gerrit/cache
    ports:
       - "29418:29418"
       - "8080:8080"
