version: '3'

configs:
  git-remote-ssh-authorized-keys:
    file: ./git-remote-ssh-authorized-keys/authorized_keys

services:
  git_remote:
    image: ssh-server:ubuntu-latest    
    volumes:
      - type: bind
        source: ./git-remote-root
        target: /git-root
      - type: bind
        source: ./git-remote-ssh-authorized-keys/authorized_keys
        target: /git/.ssh/authorized_keys
    ports:
      - "2222:22"
  redis:
    image: redis
    volumes:
      - type: bind
        source: ./redis-data
        target: /data
    ports:
      - "6379:6379"
  gerrit:
    image: gerritcodereview/gerrit
    hostname: localhost
    # Set admin API password
    # ssh localhost -p 29418 -i ./local.private.key -l admin 'gerrit set-account admin --http-password abc123'
    volumes:
      - type: bind
        source: "./${GERRIT_ROOT}/git"
        target: /var/gerrit/git
      - type: bind
        source: "./${GERRIT_ROOT}/index"
        target: /var/gerrit/index
      - type: bind
        source: "./${GERRIT_ROOT}/cache"
        target: /var/gerrit/cache
    ports:
       - "${GERRIT_PORT}:29418"
       - "${GERRIT_WEB_PORT}:8080"
